### ISSUE TITLE
Add Environment options

### ISSUE THREAD

**Issue by djarbz** [testcab/ansible-role-code-server#9]
I use a custom path for binaries and the code-server service will not source /etc/profile for the terminal.
[See this issue](https://github.com/cdr/code-server/issues/226)

I propose that you add an option for an array of environment variable to be added to the service file definition.
[Systemd Documentation](https://www.flatcar-linux.org/docs/latest/setup/systemd/environment-variables/)

**Comment by pallxk** [comment]
I've justed added the role variable `code_server_env` to configure additional environment variables. (9a88d132e0f05ff0618e83d3cf31922a72440bb0)

Try it out with `ansible-galaxy install -f pallxk.code_server,master`.

Note that `code_server_env` is a dict of variables, refer to example usage at https://github.com/testcab/ansible-role-code-server#example-playbook

I'm not using PATH in the example because I'm considering to use the user's login shell to launch code-server, so that PATH or any other environment variables configured in user's profile will be automatically sourced, avoiding duplicate configuration in code-server.

**Comment by djarbz** [comment]
Sorry for the delay in getting back to you. This should work for me, thanks.
